[package]
authors = ["Olivia Hugger <olivia@fastmail.com>"]
description = "Experimental static site generator"
name = "kg"
version = "0.0.1"

[dependencies]
comrak = "0.2.12"
nya = "0.5.1"
serde = "*"
serde_derive = "*"
toml = "*"
yaml-rust = "0.4.0"
