[package]
name = "meow"
version = "0.1.0"
authors = ["Olivia Hugger <olivia@fastmail.com>"]
description = "Experimental static site generator"

[dependencies]
nya = "0.5.0"
comrak = "0.2.12"
yaml-rust = "0.4.0"
